-- Generated by scripts/import/generate-hub-registration-migration.py.
-- Hub: unit-14-software-engineering-for-business
-- Canonical manifest SHA-256: ba95877df3853d2b7ae32c386829734797020c7dd16bb91a5517c3ebaea7473e
-- Review this file before adding it to supabase/migrations/. It never deploys itself.
begin;

select pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtextextended('hub-registration:unit-14-software-engineering-for-business', 0)
);

do $$
begin
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'hub-manifest'
      and contract.version = '1.0.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_MANIFEST_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learning-platform-core'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_CORE_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learner-api'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_LEARNER_API_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'submission'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_SUBMISSION_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1 from learning.courses as course
    where course.stable_key = 'ocr-level-3-it' and course.active
  ) then
    raise exception using errcode = '23514', message = 'HUB_COURSE_NOT_FOUND:ocr-level-3-it';
  end if;
end
$$;

insert into platform.hubs (
  id, hub_code, hub_name, description, hub_version, platform_version,
  manifest_version, core_version, learner_api_version, submission_contract_version,
  repository_url, deployment_url, activity_types, evidence_capabilities,
  features, compatibility, status, active, manifest, manifest_sha256
) values (
  '28bf16b9-26a3-5612-a184-8f1581fe2977',
  'unit-14-software-engineering-for-business',
  'Unit 14 Software Engineering for Business Hub',
  'Learner hub for OCR Level 3 IT Unit 14 Software Engineering for Business (H/507/5017). Draft foundation; not a certified production hub.',
  '0.1.0',
  '0.1.0',
  '1.0.0',
  '0.1.0',
  '0.1.0',
  '0.1.0',
  'https://github.com/Acerosa/unit-14-software-engineering-for-business-hub',
  'https://acerosa.github.io/unit-14-software-engineering-for-business-hub',
  array['classification', 'coding-exercise', 'diagnostic', 'reflection']::text[],
  array['question-level']::text[],
  '{"authentication":true,"onboarding":true,"progress":true}'::jsonb,
  '{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]}'::jsonb,
  'testing',
  true,
  '{"capabilities":{"activities":["classification","coding-exercise","diagnostic","reflection"],"evidence":["question-level"]},"certification":{"standard":"LHDS","status":"not-certified","version":"1.0.0"},"compatibility":{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]},"courses":["ocr-level-3-it"],"deploymentUrl":"https://acerosa.github.io/unit-14-software-engineering-for-business-hub","description":"Learner hub for OCR Level 3 IT Unit 14 Software Engineering for Business (H/507/5017). Draft foundation; not a certified production hub.","featureFlags":{"authentication":true,"onboarding":true,"progress":true},"hubId":"unit-14-software-engineering-for-business","manifestVersion":"1.0.0","name":"Unit 14 Software Engineering for Business Hub","repositoryUrl":"https://github.com/Acerosa/unit-14-software-engineering-for-business-hub","version":"0.1.0"}'::jsonb,
  'ba95877df3853d2b7ae32c386829734797020c7dd16bb91a5517c3ebaea7473e'
)
on conflict (hub_code) do update set
  hub_name = excluded.hub_name,
  description = excluded.description,
  hub_version = excluded.hub_version,
  platform_version = excluded.platform_version,
  manifest_version = excluded.manifest_version,
  core_version = excluded.core_version,
  learner_api_version = excluded.learner_api_version,
  submission_contract_version = excluded.submission_contract_version,
  repository_url = excluded.repository_url,
  deployment_url = excluded.deployment_url,
  activity_types = excluded.activity_types,
  evidence_capabilities = excluded.evidence_capabilities,
  features = excluded.features,
  compatibility = excluded.compatibility,
  status = excluded.status,
  active = excluded.active,
  manifest = excluded.manifest,
  manifest_sha256 = excluded.manifest_sha256,
  updated_at = clock_timestamp();

update platform.hub_course_links as link
set active = false
where link.hub_id = (select id from platform.hubs where hub_code = 'unit-14-software-engineering-for-business')
  and link.course_id not in (
    select course.id from learning.courses as course
    where course.stable_key = any (array['ocr-level-3-it']::text[])
  );

insert into platform.hub_course_links (hub_id, course_id, active)
select hub.id, course.id, true
from platform.hubs as hub
join learning.courses as course
  on course.stable_key = 'ocr-level-3-it'
where hub.hub_code = 'unit-14-software-engineering-for-business'
on conflict (hub_id, course_id) do update set active = true;

commit;
