-- Generated by scripts/import/generate-content-package-migration.py; review before applying.
-- hub_id: unit-14-software-engineering-for-business
-- content_id: unit-14-software-engineering-for-business-content
-- content_version: 0.1.0
-- source_schema_version: 0.1.0
-- generated_backend_registration_version: 0.1.0
-- OCR A1–A4 remain hub-owned; this file does not insert an assignment catalogue.
begin;

select pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtextextended('content-package:unit-14-software-engineering-for-business', 0)
);

do $$
begin
  if not exists (
    select 1 from learning.courses as course
    where course.stable_key = 'ocr-level-3-it' and course.active
  ) then
    raise exception using errcode = '23514', message = 'CONTENT_COURSE_NOT_FOUND:ocr-level-3-it';
  end if;
end
$$;

insert into learning.modules (id, course_id, stable_key, title, sort_order, active)
select
  '84c23e9d-b386-5d3c-bacb-de8e0f18dcad',
  course.id,
  'unit-14-software-engineering-for-business',
  'OCR Level 3 IT Unit 14 – Software Engineering for Business',
  14,
  true
from learning.courses as course
where course.stable_key = 'ocr-level-3-it'
  and course.active
on conflict (course_id, stable_key) do update set
  title = excluded.title,
  sort_order = excluded.sort_order,
  active = true;

insert into learning.topics (id, module_id, stable_key, title, sort_order, active)
values ('7fb55ef9-95c3-5b26-98a1-0896c474effe', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'lo1', 'Understand universal programming constructs.', 1, true)
on conflict (module_id, stable_key) do update set title = excluded.title, sort_order = excluded.sort_order, active = true;

insert into learning.topics (id, module_id, stable_key, title, sort_order, active)
values ('11c1bab2-669a-5e21-bab7-91bd3a576009', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'lo2', 'Be able to investigate business requirements for programming solutions.', 2, true)
on conflict (module_id, stable_key) do update set title = excluded.title, sort_order = excluded.sort_order, active = true;

insert into learning.topics (id, module_id, stable_key, title, sort_order, active)
values ('42e02c36-34d0-544c-b8d5-5626c5a33d5e', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'lo3', 'Be able to develop software solutions to meet business requirements.', 3, true)
on conflict (module_id, stable_key) do update set title = excluded.title, sort_order = excluded.sort_order, active = true;

insert into learning.topics (id, module_id, stable_key, title, sort_order, active)
values ('71f61666-0cf8-5b1b-b587-24ac4bf453a3', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'lo4', 'Be able to propose software solutions to meet business requirements.', 4, true)
on conflict (module_id, stable_key) do update set title = excluded.title, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('7f9d650a-3985-524c-b748-73e2d54821b5', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1', 'Programming for Business, Variables and Data Types', 1, 1, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('cbcf2885-4dee-502e-8fc3-040fc536a9e6', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-2', 'Data Type Conversion and Predefined Subroutines', 2, 2, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('a627ee60-ea09-518e-954a-714b6a3a5548', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-3', 'Selection', 3, 3, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('3dc50706-7e92-56a7-89af-060c90ff10ac', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-4', 'Iteration', 4, 4, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('2299f938-7672-52c4-9ff0-6015911ca5a5', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-5', 'Encapsulation, Parameters and Return Values', 5, 5, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('3a6c20ea-9bdd-52f5-93f4-8c16061dc321', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-6', 'GUI Objects and Assignment 1 Completion', 6, 6, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('b9dac9bb-ef14-5e24-9ce2-79ba5c42161b', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-7', 'The Modern Incremental System Life Cycle', 7, 7, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('55618d3a-cca8-5b11-84d0-d52a1fd5be5a', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-8', 'Investigating Business Requirements', 8, 8, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('d763b8d7-ef55-5746-9c1d-f5429e0a38a1', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-9', 'Feasibility, Phased Development and Assignment 2', 9, 9, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('41d1f7cf-088a-5008-97b1-4cc735ef7113', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-10', 'Design Specification, User Interface and Flow Design', 10, 10, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('9766cd5b-b326-5e54-bd76-d83d6674916e', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-11', 'Processing, Methodology and Professional House Style', 11, 11, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('62b9d1a8-961f-528a-8aa2-bc16fa299397', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-12', 'Adaptations to Design Following Stakeholder Negotiation', 12, 12, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('75f7ec3c-1604-509b-a540-b9249452c03a', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-13', 'Building the Prototype and Using Debug Tools', 13, 13, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('f7707514-24bc-5782-a7f3-90fe54fabc65', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-14', 'Testing the Prototype and Rectifying Issues', 14, 14, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('d128f262-4520-5b40-9df7-e27adeea9265', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-15', 'Design Evaluation and Assignment 3 Completion', 15, 15, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('75427851-641c-5136-a0bf-7caa69f85483', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-16', 'Presenting to an Audience', 16, 16, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('1f44f1e1-7fe7-593c-aaac-708eac491994', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-17', 'Demonstrating the Prototype to Stakeholders', 17, 17, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('f4a5f855-9d6a-56d6-996f-f59e1245957d', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-18', 'Adapting the Prototype from Stakeholder Feedback', 18, 18, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.curriculum_weeks (id, module_id, stable_key, title, week_number, sort_order, active)
values ('7c788d33-d90e-5a2d-a2a9-e6236a242aaf', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-19', 'Assignment 4 Completion, Portfolio Consolidation and Unit Review', 19, 19, true)
on conflict (module_id, stable_key) do update set title = excluded.title, week_number = excluded.week_number, sort_order = excluded.sort_order, active = true;

insert into learning.groups (
  id, academic_year_id, course_id, code, name, active, year_group, registration_key, registration_open
)
select
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  academic_year.id,
  course.id,
  'UNIT14-TEST-A',
  'Unit 14 Synthetic Test Group A',
  true,
  'Year 1',
  'unit14-year-1-test',
  false
from learning.courses as course
join lateral (
  select candidate.id from learning.academic_years as candidate
  where candidate.active order by candidate.code limit 1
) as academic_year on true
where course.stable_key = 'ocr-level-3-it' and course.active
on conflict (academic_year_id, course_id, code) do update set
  name = excluded.name, active = excluded.active, year_group = excluded.year_group,
  registration_key = excluded.registration_key, registration_open = excluded.registration_open;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('146b91ab-7e2e-5f82-90fa-f2f7dc2a321e', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-assignment-1-guide', 'Assignment 1 technical-guide starter', 'reflection', 'content/unit-14/activities/week-1-assignment-1-guide', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('7a26652c-f6e7-592e-93e9-0663eecb6aa8', '146b91ab-7e2e-5f82-90fa-f2f7dc2a321e', '0.1.0', '1ff692010d08501bd64a824ead32de2e78ff7b717a6e0e5edd4410e5995a8d76', 1, 1, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '1bbdac81-522e-5bfe-a2b3-0dbabe0828f2',
  '7a26652c-f6e7-592e-93e9-0663eecb6aa8',
  'u14-w1-a1-notes',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-a1-notes',
  1,
  1
from learning.activity_versions as version
where version.id = '7a26652c-f6e7-592e-93e9-0663eecb6aa8'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '1bbdac81-522e-5bfe-a2b3-0dbabe0828f2'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '1bbdac81-522e-5bfe-a2b3-0dbabe0828f2'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '7a26652c-f6e7-592e-93e9-0663eecb6aa8'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '7a26652c-f6e7-592e-93e9-0663eecb6aa8',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  2,
  5,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '7a26652c-f6e7-592e-93e9-0663eecb6aa8'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '61061ea1-1364-539a-93fd-9625648c5b56',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '7a26652c-f6e7-592e-93e9-0663eecb6aa8',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('13dd90bf-9306-5b04-907a-124e20726186', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-baseline-diagnostic', 'Baseline programming diagnostic', 'diagnostic', 'content/unit-14/activities/week-1-baseline-diagnostic', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('f1f193ef-4488-574d-b2c4-4b78790ec219', '13dd90bf-9306-5b04-907a-124e20726186', '0.1.0', '295037cb60afe96fade05fb2d7fcff9ed33cc101d53266082c2a0bffd8a48e78', 4, 4, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '4f9adab5-0828-50d7-8d15-84622f8f242b',
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  'u14-w1-base-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-base-q1',
  1,
  1
from learning.activity_versions as version
where version.id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"a","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '4f9adab5-0828-50d7-8d15-84622f8f242b'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '4f9adab5-0828-50d7-8d15-84622f8f242b'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '7f49d43e-be52-55a5-9f8a-158c307acbdb',
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  'u14-w1-base-q2',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-base-q2',
  2,
  1
from learning.activity_versions as version
where version.id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"c","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7f49d43e-be52-55a5-9f8a-158c307acbdb'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7f49d43e-be52-55a5-9f8a-158c307acbdb'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '8a3b145b-fa71-50b0-b1e7-f424c89a0845',
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  'u14-w1-base-q3',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-base-q3',
  3,
  1
from learning.activity_versions as version
where version.id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"b","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8a3b145b-fa71-50b0-b1e7-f424c89a0845'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8a3b145b-fa71-50b0-b1e7-f424c89a0845'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '31ce64e6-b0d6-5bcb-89a5-85704498ea3f',
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  'u14-w1-base-q4',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-base-q4',
  4,
  1
from learning.activity_versions as version
where version.id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '31ce64e6-b0d6-5bcb-89a5-85704498ea3f'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '31ce64e6-b0d6-5bcb-89a5-85704498ea3f'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  1,
  1,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = 'f1f193ef-4488-574d-b2c4-4b78790ec219'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  'b99e618d-ab6b-596e-bcae-0e9cd8471301',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  'f1f193ef-4488-574d-b2c4-4b78790ec219',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('823b4151-3b2e-51f1-a34c-a62eec9f4320', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-business-data-explorer', 'Business data explorer', 'classification', 'content/unit-14/activities/week-1-business-data-explorer', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('4a7930da-8962-5e73-9441-9ead0865722e', '823b4151-3b2e-51f1-a34c-a62eec9f4320', '0.1.0', '320c5b05fe2a135885ec33777f5dd602af750a14dad0c17cf828e003a730ee79', 6, 6, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'fab6ab3e-b619-582d-abb8-75861b1e5e75',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-class:customer-name',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-biz-class:customer-name',
  1,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"string","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'fab6ab3e-b619-582d-abb8-75861b1e5e75'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'fab6ab3e-b619-582d-abb8-75861b1e5e75'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '7e4ecdd7-d577-5fc4-91f0-0b35638ceed3',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-class:item-quantity',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-biz-class:item-quantity',
  2,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"integer","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7e4ecdd7-d577-5fc4-91f0-0b35638ceed3'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7e4ecdd7-d577-5fc4-91f0-0b35638ceed3'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'a17df2ae-f472-5e85-af2b-4bcb18806400',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-class:unit-price',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-biz-class:unit-price',
  3,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"floating-point","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a17df2ae-f472-5e85-af2b-4bcb18806400'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a17df2ae-f472-5e85-af2b-4bcb18806400'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'a03a5d27-4d48-54c4-b1ee-3426f6959215',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-class:delivery-flag',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-biz-class:delivery-flag',
  4,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"boolean","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a03a5d27-4d48-54c4-b1ee-3426f6959215'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a03a5d27-4d48-54c4-b1ee-3426f6959215'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'fee63ac1-0e1b-5ed5-93b5-d0e6218c54c0',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-why',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-biz-why',
  5,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'fee63ac1-0e1b-5ed5-93b5-d0e6218c54c0'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'fee63ac1-0e1b-5ed5-93b5-d0e6218c54c0'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '621a573a-4a3f-5009-8a6c-5042e1e65f6a',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  'u14-w1-biz-ref',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-biz-ref',
  6,
  1
from learning.activity_versions as version
where version.id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '621a573a-4a3f-5009-8a6c-5042e1e65f6a'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '621a573a-4a3f-5009-8a6c-5042e1e65f6a'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '4a7930da-8962-5e73-9441-9ead0865722e'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '4a7930da-8962-5e73-9441-9ead0865722e',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  1,
  2,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '4a7930da-8962-5e73-9441-9ead0865722e'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '80395b29-0736-5356-a4e2-db83178f14fc',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '4a7930da-8962-5e73-9441-9ead0865722e',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('14f868eb-0125-5b57-a751-d56eb908c385', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-first-commits', 'Clone, commits and push', 'diagnostic', 'content/unit-14/activities/week-1-first-commits', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('e7f0641d-068e-5ed1-a6f6-dd2952add4a0', '14f868eb-0125-5b57-a751-d56eb908c385', '0.1.0', '902464dff63de187c598694c2e6914fe7eca9f1ac74abc588756ae83a1f13460', 2, 2, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'b6ede472-b488-56cf-8964-33345ffdf102',
  'e7f0641d-068e-5ed1-a6f6-dd2952add4a0',
  'u14-w1-commit-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-commit-q1',
  1,
  1
from learning.activity_versions as version
where version.id = 'e7f0641d-068e-5ed1-a6f6-dd2952add4a0'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"b","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'b6ede472-b488-56cf-8964-33345ffdf102'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'b6ede472-b488-56cf-8964-33345ffdf102'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '7bbb6583-02d0-5bca-8312-fa5aaac8abbd',
  'e7f0641d-068e-5ed1-a6f6-dd2952add4a0',
  'u14-w1-commit-ref',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-commit-ref',
  2,
  1
from learning.activity_versions as version
where version.id = 'e7f0641d-068e-5ed1-a6f6-dd2952add4a0'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7bbb6583-02d0-5bca-8312-fa5aaac8abbd'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '7bbb6583-02d0-5bca-8312-fa5aaac8abbd'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = 'e7f0641d-068e-5ed1-a6f6-dd2952add4a0'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  'e7f0641d-068e-5ed1-a6f6-dd2952add4a0',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  2,
  3,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = 'e7f0641d-068e-5ed1-a6f6-dd2952add4a0'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  'be4ef7b1-5934-576e-b5e8-d9801229af89',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  'e7f0641d-068e-5ed1-a6f6-dd2952add4a0',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('3662dc66-8c26-5100-8b93-bfddea7d07a7', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-first-python-business-program', 'First Python business-order program', 'coding-exercise', 'content/unit-14/activities/week-1-first-python-business-program', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('29c33c49-fa24-53e6-8e9c-330ee48a3a9c', '3662dc66-8c26-5100-8b93-bfddea7d07a7', '0.1.0', 'f56f17910cdacfb467b78d300ab098a2bf34f4de3d5cc3436817a0f3b1e7fe17', 2, 2, null)
on conflict (activity_id, version) do nothing;

insert into learning.activity_version_languages (activity_version_id, coding_language_id)
select version.id, coding_language.id
from learning.activity_versions as version
join learning.coding_languages as coding_language
  on coding_language.stable_key = 'python' and coding_language.active
where version.id = '29c33c49-fa24-53e6-8e9c-330ee48a3a9c'
  and version.published_at is null
on conflict (activity_version_id, coding_language_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '8126e826-c19f-5458-b55d-2c522cc5ee00',
  '29c33c49-fa24-53e6-8e9c-330ee48a3a9c',
  'u14-w1-order-code',
  'week-1',
  'Week 1',
  'code-editor',
  'u14-w1-order-code',
  1,
  1
from learning.activity_versions as version
where version.id = '29c33c49-fa24-53e6-8e9c-330ee48a3a9c'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"python-patterns","prohibited":[],"required":["input[[:space:]]*\\(","print[[:space:]]*\\(","customer_name|quantity|unit_price|delivery"]}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8126e826-c19f-5458-b55d-2c522cc5ee00'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8126e826-c19f-5458-b55d-2c522cc5ee00'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '31158ed7-e952-53d7-aea5-65d3f50838c9',
  '29c33c49-fa24-53e6-8e9c-330ee48a3a9c',
  'u14-w1-order-ref',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-order-ref',
  2,
  1
from learning.activity_versions as version
where version.id = '29c33c49-fa24-53e6-8e9c-330ee48a3a9c'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '31158ed7-e952-53d7-aea5-65d3f50838c9'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '31158ed7-e952-53d7-aea5-65d3f50838c9'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '29c33c49-fa24-53e6-8e9c-330ee48a3a9c'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '29c33c49-fa24-53e6-8e9c-330ee48a3a9c',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  2,
  4,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '29c33c49-fa24-53e6-8e9c-330ee48a3a9c'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  'b1429fe5-2101-54df-878c-511af47e6c0f',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '29c33c49-fa24-53e6-8e9c-330ee48a3a9c',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('c1d434bf-a35b-5b01-a488-1c24d4d512b7', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-github-classroom-guidance', 'GitHub Classroom and the Python environment', 'diagnostic', 'content/unit-14/activities/week-1-github-classroom-guidance', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('d1ff67ee-67d7-5ed0-965e-94cefa1289ae', 'c1d434bf-a35b-5b01-a488-1c24d4d512b7', '0.1.0', '2a32d5e90f60972573d9a1bd2ccb9a1850856aa9771af3923e8565bc24ea2808', 2, 2, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '84fab744-5065-5c70-b3f1-cdc277f74f86',
  'd1ff67ee-67d7-5ed0-965e-94cefa1289ae',
  'u14-w1-gh-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-gh-q1',
  1,
  1
from learning.activity_versions as version
where version.id = 'd1ff67ee-67d7-5ed0-965e-94cefa1289ae'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"b","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '84fab744-5065-5c70-b3f1-cdc277f74f86'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '84fab744-5065-5c70-b3f1-cdc277f74f86'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '2dbb3229-302d-525a-8652-32b3386e22ca',
  'd1ff67ee-67d7-5ed0-965e-94cefa1289ae',
  'u14-w1-gh-ref',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-gh-ref',
  2,
  1
from learning.activity_versions as version
where version.id = 'd1ff67ee-67d7-5ed0-965e-94cefa1289ae'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '2dbb3229-302d-525a-8652-32b3386e22ca'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '2dbb3229-302d-525a-8652-32b3386e22ca'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = 'd1ff67ee-67d7-5ed0-965e-94cefa1289ae'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  'd1ff67ee-67d7-5ed0-965e-94cefa1289ae',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  1,
  5,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = 'd1ff67ee-67d7-5ed0-965e-94cefa1289ae'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '955697d7-491e-5197-aa87-0c247f0c5924',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  'd1ff67ee-67d7-5ed0-965e-94cefa1289ae',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('031975d9-662c-51b3-8321-76f21cfafd73', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-guided-business-data', 'Guided business-data practice', 'classification', 'content/unit-14/activities/week-1-guided-business-data', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('6e5b59d5-fb11-59fb-bc73-43b6f59b180f', '031975d9-662c-51b3-8321-76f21cfafd73', '0.1.0', 'b02f8596bb28bdf8a708910f2a465d9f122f1fea78470325cad69c3fd3ef132f', 6, 6, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '9866693e-b750-5d18-a5c6-781655bc8d9b',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-class:drink-name',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-guided-class:drink-name',
  1,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"string","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '9866693e-b750-5d18-a5c6-781655bc8d9b'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '9866693e-b750-5d18-a5c6-781655bc8d9b'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'c0ffdbfd-a6b1-509c-a04a-4b0efb6eac99',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-class:cup-count',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-guided-class:cup-count',
  2,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"integer","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'c0ffdbfd-a6b1-509c-a04a-4b0efb6eac99'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'c0ffdbfd-a6b1-509c-a04a-4b0efb6eac99'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '680365ef-70bb-528f-b03c-2a2a49a49b49',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-class:price',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-guided-class:price',
  3,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"floating-point","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '680365ef-70bb-528f-b03c-2a2a49a49b49'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '680365ef-70bb-528f-b03c-2a2a49a49b49'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'a37a9931-6f6b-53b6-9c64-6ef46acf0cf6',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-class:loyalty',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-guided-class:loyalty',
  4,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"boolean","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a37a9931-6f6b-53b6-9c64-6ef46acf0cf6'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'a37a9931-6f6b-53b6-9c64-6ef46acf0cf6'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '53ca111c-192c-544f-a82e-d735a3a42e5f',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-class:notes',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-guided-class:notes',
  5,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"string","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '53ca111c-192c-544f-a82e-d735a3a42e5f'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '53ca111c-192c-544f-a82e-d735a3a42e5f'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'dad7f77a-9cc4-5e2e-84f9-80481c4fb13c',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  'u14-w1-guided-why',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-guided-why',
  6,
  1
from learning.activity_versions as version
where version.id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'dad7f77a-9cc4-5e2e-84f9-80481c4fb13c'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'dad7f77a-9cc4-5e2e-84f9-80481c4fb13c'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  2,
  2,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '6e5b59d5-fb11-59fb-bc73-43b6f59b180f'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '8343b6a1-58f5-5b36-bd73-4ee51df4986a',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '6e5b59d5-fb11-59fb-bc73-43b6f59b180f',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('93c56797-b578-5a96-ad56-6f833b601707', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-homework-extension', 'Homework: extend the business-order program', 'coding-exercise', 'content/unit-14/activities/week-1-homework-extension', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9', '93c56797-b578-5a96-ad56-6f833b601707', '0.1.0', '393bcdd960e58904105e45584e73f280371677435567de09eb0c05a1b23a2824', 2, 2, null)
on conflict (activity_id, version) do nothing;

insert into learning.activity_version_languages (activity_version_id, coding_language_id)
select version.id, coding_language.id
from learning.activity_versions as version
join learning.coding_languages as coding_language
  on coding_language.stable_key = 'python' and coding_language.active
where version.id = '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9'
  and version.published_at is null
on conflict (activity_version_id, coding_language_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'df81915d-d9d3-52ff-abc1-b03fb140b90f',
  '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9',
  'u14-w1-hw-code',
  'week-1',
  'Week 1',
  'code-editor',
  'u14-w1-hw-code',
  1,
  1
from learning.activity_versions as version
where version.id = '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"python-patterns","prohibited":[],"required":["input[[:space:]]*\\(","print[[:space:]]*\\(","="]}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'df81915d-d9d3-52ff-abc1-b03fb140b90f'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'df81915d-d9d3-52ff-abc1-b03fb140b90f'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '268d91ac-d3eb-55b1-90a6-f74f5d049161',
  '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9',
  'u14-w1-hw-ref',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-hw-ref',
  2,
  1
from learning.activity_versions as version
where version.id = '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '268d91ac-d3eb-55b1-90a6-f74f5d049161'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '268d91ac-d3eb-55b1-90a6-f74f5d049161'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  3,
  1,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '8023d8f6-b194-5d00-b1d1-52c7b7285b22',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '1cba0719-fb5b-51a4-9c77-ec0a5db3d7e9',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('d111a0db-aad5-5abd-9b5a-90e4a9dbd78f', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-input-and-output', 'Print and input', 'coding-exercise', 'content/unit-14/activities/week-1-input-and-output', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('40eaf59d-96e1-5e53-b6f2-9386fb26c901', 'd111a0db-aad5-5abd-9b5a-90e4a9dbd78f', '0.1.0', 'fa85999eacf75823713e64fc5593d8081801d776f4f0ae60bfd4a5b73ab830a6', 2, 2, null)
on conflict (activity_id, version) do nothing;

insert into learning.activity_version_languages (activity_version_id, coding_language_id)
select version.id, coding_language.id
from learning.activity_versions as version
join learning.coding_languages as coding_language
  on coding_language.stable_key = 'python' and coding_language.active
where version.id = '40eaf59d-96e1-5e53-b6f2-9386fb26c901'
  and version.published_at is null
on conflict (activity_version_id, coding_language_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'c2152b63-76d0-543d-ab9a-f6935ebade5b',
  '40eaf59d-96e1-5e53-b6f2-9386fb26c901',
  'u14-w1-io-code',
  'week-1',
  'Week 1',
  'code-editor',
  'u14-w1-io-code',
  1,
  1
from learning.activity_versions as version
where version.id = '40eaf59d-96e1-5e53-b6f2-9386fb26c901'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"python-patterns","prohibited":[],"required":["input[[:space:]]*\\(","print[[:space:]]*\\(","="]}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'c2152b63-76d0-543d-ab9a-f6935ebade5b'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'c2152b63-76d0-543d-ab9a-f6935ebade5b'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '4be105e7-173c-5b87-81a7-b981e2622bfd',
  '40eaf59d-96e1-5e53-b6f2-9386fb26c901',
  'u14-w1-io-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-io-q1',
  2,
  1
from learning.activity_versions as version
where version.id = '40eaf59d-96e1-5e53-b6f2-9386fb26c901'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"b","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '4be105e7-173c-5b87-81a7-b981e2622bfd'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '4be105e7-173c-5b87-81a7-b981e2622bfd'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '40eaf59d-96e1-5e53-b6f2-9386fb26c901'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '40eaf59d-96e1-5e53-b6f2-9386fb26c901',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  1,
  4,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '40eaf59d-96e1-5e53-b6f2-9386fb26c901'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  '04fd1dbf-f742-545e-9c2f-eebfd2741a76',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '40eaf59d-96e1-5e53-b6f2-9386fb26c901',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('86bcaf28-058d-5298-a8ed-7ee14ed8c071', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-review', 'Week 1 retrieval', 'classification', 'content/unit-14/activities/week-1-review', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('372e5eec-1d26-5cc0-8ee4-31fc8192fbc4', '86bcaf28-058d-5298-a8ed-7ee14ed8c071', '0.1.0', '06761e72200a835a138640a767894264a112875daa965f1b9c46b8299c2d9562', 4, 4, null)
on conflict (activity_id, version) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'ff22972c-5b63-5d4d-946b-7adfa850ff06',
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  'u14-w1-rev-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-rev-q1',
  1,
  1
from learning.activity_versions as version
where version.id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"string","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ff22972c-5b63-5d4d-946b-7adfa850ff06'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ff22972c-5b63-5d4d-946b-7adfa850ff06'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '786464b0-56aa-5c74-a8f2-8c908e3551e5',
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  'u14-w1-rev-q2',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-rev-q2',
  2,
  1
from learning.activity_versions as version
where version.id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"b","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '786464b0-56aa-5c74-a8f2-8c908e3551e5'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '786464b0-56aa-5c74-a8f2-8c908e3551e5'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '490201f7-0ad8-5f07-8da7-22a7552c78b2',
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  'u14-w1-rev-class:stock-count',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-rev-class:stock-count',
  3,
  1
from learning.activity_versions as version
where version.id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"integer","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '490201f7-0ad8-5f07-8da7-22a7552c78b2'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '490201f7-0ad8-5f07-8da7-22a7552c78b2'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'ef6a866b-847e-5cfd-b6b6-39cccb5e259e',
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  'u14-w1-rev-class:paid',
  'week-1',
  'Week 1',
  'matching',
  'u14-w1-rev-class:paid',
  4,
  1
from learning.activity_versions as version
where version.id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctCategoryId":"boolean","mode":"classification"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ef6a866b-847e-5cfd-b6b6-39cccb5e259e'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ef6a866b-847e-5cfd-b6b6-39cccb5e259e'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  2,
  1,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  'f2e214cf-f315-557f-980d-73361a5425e1',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  '372e5eec-1d26-5cc0-8ee4-31fc8192fbc4',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

insert into learning.activities (id, module_id, stable_key, title, activity_type, git_path, active)
values ('a04a2cc0-55af-523e-95e5-a0049f411b0f', '84c23e9d-b386-5d3c-bacb-de8e0f18dcad', 'week-1-variables-and-data-types', 'Variables and fundamental data types', 'coding-exercise', 'content/unit-14/activities/week-1-variables-and-data-types', true)
on conflict (stable_key) do update set title = excluded.title, activity_type = excluded.activity_type, git_path = excluded.git_path, active = true;

insert into learning.activity_versions (id, activity_id, version, content_hash, max_score, question_count, published_at)
values ('e8c2324c-963a-55a3-a2f1-137e3be51ade', 'a04a2cc0-55af-523e-95e5-a0049f411b0f', '0.1.0', 'f965b6f6a65f0f99558dc0c03f99958c6616941ee4ef7a983fc01f3d123f0d55', 3, 3, null)
on conflict (activity_id, version) do nothing;

insert into learning.activity_version_languages (activity_version_id, coding_language_id)
select version.id, coding_language.id
from learning.activity_versions as version
join learning.coding_languages as coding_language
  on coding_language.stable_key = 'python' and coding_language.active
where version.id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
  and version.published_at is null
on conflict (activity_version_id, coding_language_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '8b6cf65c-37ad-5311-bba4-b1cc3c03af07',
  'e8c2324c-963a-55a3-a2f1-137e3be51ade',
  'u14-w1-var-code',
  'week-1',
  'Week 1',
  'code-editor',
  'u14-w1-var-code',
  1,
  1
from learning.activity_versions as version
where version.id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8b6cf65c-37ad-5311-bba4-b1cc3c03af07'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '8b6cf65c-37ad-5311-bba4-b1cc3c03af07'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  '371cf564-b9f0-524a-80ec-ec54b8b8a0a7',
  'e8c2324c-963a-55a3-a2f1-137e3be51ade',
  'u14-w1-var-q1',
  'week-1',
  'Week 1',
  'single',
  'u14-w1-var-q1',
  2,
  1
from learning.activity_versions as version
where version.id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"correctOptionId":"boolean","mode":"single-choice"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '371cf564-b9f0-524a-80ec-ec54b8b8a0a7'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = '371cf564-b9f0-524a-80ec-ec54b8b8a0a7'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

insert into learning.questions (
  id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
)
select
  'ec82ccaf-0aa9-53e7-8e4e-146c0e994041',
  'e8c2324c-963a-55a3-a2f1-137e3be51ade',
  'u14-w1-var-why',
  'week-1',
  'Week 1',
  'text',
  'u14-w1-var-why',
  3,
  1
from learning.activity_versions as version
where version.id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
  and version.published_at is null
on conflict (activity_version_id, stable_key) do nothing;

insert into learning.question_marking (question_id, spec)
select question.id, '{"mode":"completion"}'::jsonb
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ec82ccaf-0aa9-53e7-8e4e-146c0e994041'
  and version.published_at is null
on conflict (question_id) do nothing;

insert into learning.question_topics (question_id, topic_id, weight)
select question.id, '7fb55ef9-95c3-5b26-98a1-0896c474effe', 1
from learning.questions as question
join learning.activity_versions as version on version.id = question.activity_version_id
where question.id = 'ec82ccaf-0aa9-53e7-8e4e-146c0e994041'
  and version.published_at is null
on conflict (question_id, topic_id) do nothing;

update learning.activity_versions
set published_at = '2026-08-13T12:00:00Z'::timestamptz
where id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
  and published_at is null;

insert into learning.activity_delivery (
  activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
)
select
  'e8c2324c-963a-55a3-a2f1-137e3be51ade',
  academic_year.id,
  '7f9d650a-3985-524c-b748-73e2d54821b5',
  1,
  1,
  3,
  true
from learning.academic_years as academic_year
where academic_year.active
  and not exists (
    select 1 from learning.activity_delivery as delivery
    where delivery.activity_version_id = 'e8c2324c-963a-55a3-a2f1-137e3be51ade'
      and delivery.academic_year_id = academic_year.id
      and delivery.group_id is null
  )
order by academic_year.code
limit 1;

insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
select
  'f2077c5f-5ed5-5e01-a83b-33faddfe3cd9',
  '8e3fa246-6ebb-5488-8625-8adb5242fe42',
  'e8c2324c-963a-55a3-a2f1-137e3be51ade',
  true,
  true
on conflict (group_id, activity_version_id) do update set required = excluded.required, active = excluded.active;

commit;
