-- Register the two reviewed learner hubs into the authoritative Hub Registry.
-- Generated from supabase/data/manifests/hubs/*/learning-platform-hub.json
-- via scripts/import/generate-hub-registration-migration.py
-- (--status production --active).
--
-- Does not mark hubs certified (manifests omit certification).
-- Does not alter learner curriculum, groups, enrolments or attempts.

-- Generated by scripts/import/generate-hub-registration-migration.py.
-- Hub: unit-3-cyber-security
-- Canonical manifest SHA-256: a70bfff2a97134de8d534344612e2d48fa1a8ba68b95fc9390469e674a733bb2
-- Review this file before adding it to supabase/migrations/. It never deploys itself.
begin;

select pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtextextended('hub-registration:unit-3-cyber-security', 0)
);

do $$
begin
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'hub-manifest'
      and contract.version = '1.0.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_MANIFEST_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learning-platform-core'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_CORE_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learner-api'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_LEARNER_API_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'submission'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_SUBMISSION_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1 from learning.courses as course
    where course.stable_key = 'ocr-level-3-it' and course.active
  ) then
    raise exception using errcode = '23514', message = 'HUB_COURSE_NOT_FOUND:ocr-level-3-it';
  end if;
end
$$;

insert into platform.hubs (
  id, hub_code, hub_name, description, hub_version, platform_version,
  manifest_version, core_version, learner_api_version, submission_contract_version,
  repository_url, deployment_url, activity_types, evidence_capabilities,
  features, compatibility, status, active, manifest, manifest_sha256
) values (
  'e8951af1-5d41-5fc8-9277-a89acdd4b8bf',
  'unit-3-cyber-security',
  'Unit 3 Cyber Security Hub',
  'Learner hub for OCR Level 3 IT Unit 3 Cyber Security.',
  '0.1.0',
  '0.1.0',
  '1.0.0',
  '0.1.0',
  '0.1.0',
  '0.1.0',
  'https://github.com/Acerosa/unit-3-Cyber-Security-Hub',
  'https://acerosa.github.io/unit-3-Cyber-Security-Hub',
  array['classification', 'matching', 'reflection', 'retrieval-quiz']::text[],
  array['question-level']::text[],
  '{"authentication":true,"onboarding":true,"progress":true}'::jsonb,
  '{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]}'::jsonb,
  'production',
  true,
  '{"capabilities":{"activities":["classification","matching","reflection","retrieval-quiz"],"evidence":["question-level"]},"compatibility":{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]},"courses":["ocr-level-3-it"],"deploymentUrl":"https://acerosa.github.io/unit-3-Cyber-Security-Hub","description":"Learner hub for OCR Level 3 IT Unit 3 Cyber Security.","featureFlags":{"authentication":true,"onboarding":true,"progress":true},"hubId":"unit-3-cyber-security","manifestVersion":"1.0.0","name":"Unit 3 Cyber Security Hub","repositoryUrl":"https://github.com/Acerosa/unit-3-Cyber-Security-Hub","version":"0.1.0"}'::jsonb,
  'a70bfff2a97134de8d534344612e2d48fa1a8ba68b95fc9390469e674a733bb2'
)
on conflict (hub_code) do update set
  hub_name = excluded.hub_name,
  description = excluded.description,
  hub_version = excluded.hub_version,
  platform_version = excluded.platform_version,
  manifest_version = excluded.manifest_version,
  core_version = excluded.core_version,
  learner_api_version = excluded.learner_api_version,
  submission_contract_version = excluded.submission_contract_version,
  repository_url = excluded.repository_url,
  deployment_url = excluded.deployment_url,
  activity_types = excluded.activity_types,
  evidence_capabilities = excluded.evidence_capabilities,
  features = excluded.features,
  compatibility = excluded.compatibility,
  status = excluded.status,
  active = excluded.active,
  manifest = excluded.manifest,
  manifest_sha256 = excluded.manifest_sha256,
  updated_at = clock_timestamp();

update platform.hub_course_links as link
set active = false
where link.hub_id = (select id from platform.hubs where hub_code = 'unit-3-cyber-security')
  and link.course_id not in (
    select course.id from learning.courses as course
    where course.stable_key = any (array['ocr-level-3-it']::text[])
  );

insert into platform.hub_course_links (hub_id, course_id, active)
select hub.id, course.id, true
from platform.hubs as hub
join learning.courses as course
  on course.stable_key = 'ocr-level-3-it'
where hub.hub_code = 'unit-3-cyber-security'
on conflict (hub_id, course_id) do update set active = true;

commit;

-- Generated by scripts/import/generate-hub-registration-migration.py.
-- Hub: tlevel-software-development
-- Canonical manifest SHA-256: e6e99790906b111616d25a9dace84d308671fa6a0a16915604fa3f041aec4c57
-- Review this file before adding it to supabase/migrations/. It never deploys itself.
begin;

select pg_catalog.pg_advisory_xact_lock(
  pg_catalog.hashtextextended('hub-registration:tlevel-software-development', 0)
);

do $$
begin
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'hub-manifest'
      and contract.version = '1.0.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_MANIFEST_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learning-platform-core'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_CORE_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'learner-api'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_LEARNER_API_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1
    from platform.contract_versions as contract
    where contract.contract_key = 'submission'
      and contract.version = '0.1.0'
      and contract.status = 'active'
  ) then
    raise exception using errcode = '23514', message = 'HUB_SUBMISSION_VERSION_UNSUPPORTED';
  end if;
  if not exists (
    select 1 from learning.courses as course
    where course.stable_key = 't-level-digital-software-development' and course.active
  ) then
    raise exception using errcode = '23514', message = 'HUB_COURSE_NOT_FOUND:t-level-digital-software-development';
  end if;
end
$$;

insert into platform.hubs (
  id, hub_code, hub_name, description, hub_version, platform_version,
  manifest_version, core_version, learner_api_version, submission_contract_version,
  repository_url, deployment_url, activity_types, evidence_capabilities,
  features, compatibility, status, active, manifest, manifest_sha256
) values (
  'b08ab36e-a16a-5378-8bec-09e699cc2599',
  'tlevel-software-development',
  'T Level Digital Software Development Hub',
  'Learner hub for T Level Digital Software Development.',
  '0.1.0',
  '0.1.0',
  '1.0.0',
  '0.1.0',
  '0.1.0',
  '0.1.0',
  'https://github.com/Acerosa/tlevel-software-development-hub',
  'https://acerosa.github.io/tlevel-software-development-hub',
  array['classification', 'coding-exercise', 'diagnostic']::text[],
  array['question-level']::text[],
  '{"authentication":true,"codingExercises":true,"onboarding":true,"progress":true}'::jsonb,
  '{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]}'::jsonb,
  'production',
  true,
  '{"capabilities":{"activities":["classification","coding-exercise","diagnostic"],"evidence":["question-level"]},"compatibility":{"required":{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"},"testedCombinations":[{"coreVersion":"0.1.0","learnerApiContractVersion":"0.1.0","submissionContractVersion":"0.1.0"}]},"courses":["t-level-digital-software-development"],"deploymentUrl":"https://acerosa.github.io/tlevel-software-development-hub","description":"Learner hub for T Level Digital Software Development.","featureFlags":{"authentication":true,"codingExercises":true,"onboarding":true,"progress":true},"hubId":"tlevel-software-development","manifestVersion":"1.0.0","name":"T Level Digital Software Development Hub","repositoryUrl":"https://github.com/Acerosa/tlevel-software-development-hub","version":"0.1.0"}'::jsonb,
  'e6e99790906b111616d25a9dace84d308671fa6a0a16915604fa3f041aec4c57'
)
on conflict (hub_code) do update set
  hub_name = excluded.hub_name,
  description = excluded.description,
  hub_version = excluded.hub_version,
  platform_version = excluded.platform_version,
  manifest_version = excluded.manifest_version,
  core_version = excluded.core_version,
  learner_api_version = excluded.learner_api_version,
  submission_contract_version = excluded.submission_contract_version,
  repository_url = excluded.repository_url,
  deployment_url = excluded.deployment_url,
  activity_types = excluded.activity_types,
  evidence_capabilities = excluded.evidence_capabilities,
  features = excluded.features,
  compatibility = excluded.compatibility,
  status = excluded.status,
  active = excluded.active,
  manifest = excluded.manifest,
  manifest_sha256 = excluded.manifest_sha256,
  updated_at = clock_timestamp();

update platform.hub_course_links as link
set active = false
where link.hub_id = (select id from platform.hubs where hub_code = 'tlevel-software-development')
  and link.course_id not in (
    select course.id from learning.courses as course
    where course.stable_key = any (array['t-level-digital-software-development']::text[])
  );

insert into platform.hub_course_links (hub_id, course_id, active)
select hub.id, course.id, true
from platform.hubs as hub
join learning.courses as course
  on course.stable_key = 't-level-digital-software-development'
where hub.hub_code = 'tlevel-software-development'
on conflict (hub_id, course_id) do update set active = true;

commit;
