#!/usr/bin/env python3
"""Generate Unit 3 Batch B marking-normalisation migrations.

Published activity versions are immutable. Batch B copies forward canonical
question stable_keys onto the next semver, attaches marking specs, and leaves
previous published versions and learner evidence unchanged.

Week 5 activities that already have complete correct specs are not versioned.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_unit3_batch_a1 import NAMESPACE, sql_literal
from unit3_batch_b_sources import build_policies

BACKEND_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_DIR = BACKEND_ROOT / "supabase/data/manifests/unit3-batch-b"
MIGRATION_DIR = BACKEND_ROOT / "supabase/migrations"
PUBLISHED_AT = "2026-08-30T22:30:00Z"
UUID_NS = str(NAMESPACE)

WEEK_GROUPS = (
    ("20260830230100_unit3_batch_b_week1.sql", {1}),
    ("20260830230200_unit3_batch_b_weeks_2_3.sql", {2, 3}),
    ("20260830230300_unit3_batch_b_weeks_4_5.sql", {4, 5}),
    ("20260830230400_unit3_batch_b_weeks_6_7.sql", {6, 7}),
)


def slim_catalogue(rows: list[dict]) -> list[dict]:
    keys = (
        "activity_key",
        "title",
        "git_path",
        "version",
        "version_id",
        "published",
        "question_count",
        "max_score",
        "week_number",
        "session_number",
        "question_id",
        "question_key",
        "question_type",
        "ordinal",
        "q_max",
        "section_key",
        "section_title",
        "marking_spec",
    )
    return [{key: row.get(key) for key in keys} for row in rows]


def compact_question(policy: dict) -> dict:
    item = {"k": policy["questionKey"], "m": policy["mode"]}
    if policy.get("correctOptionId"):
        item["o"] = policy["correctOptionId"]
    if policy.get("correctCategoryId"):
        item["c"] = policy["correctCategoryId"]
    if policy.get("newQuestionType"):
        item["qt"] = policy["newQuestionType"]
    if policy.get("newMaxScore") is not None:
        item["ms"] = policy["newMaxScore"]
    return item


def compact_activities(policies: list[dict]) -> list[dict]:
    grouped: dict[str, dict] = {}
    for policy in policies:
        if policy["action"] != "version":
            continue
        activity = grouped.setdefault(
            policy["activityKey"],
            {
                "activityKey": policy["activityKey"],
                "sourceVersion": policy["sourceVersion"],
                "newVersion": policy["newVersion"],
                "weekNumber": policy["weekNumber"],
                "sessionNumber": policy["sessionNumber"],
                "questions": [],
            },
        )
        activity["questions"].append(compact_question(policy))
    return [grouped[key] for key in sorted(grouped)]


def emit_week_migration(filename: str, activities: list[dict]) -> str:
    payload = json.dumps(activities, separators=(",", ":"), ensure_ascii=False)
    return "\n".join(
        [
            "-- Generated by scripts/import/generate_unit3_batch_b.py; do not edit manually.",
            "-- Batch B marking normalisation. Does not mutate published versions,",
            "-- learner evidence, schema_migrations, or curriculum publications.",
            "begin;",
            "",
            f"select learning.apply_unit3_batch_b_marking($unit3batchb${payload}$unit3batchb$::jsonb);",
            "",
            "commit;",
            "",
        ]
    )


def runtime_sql() -> str:
    ns = sql_literal(UUID_NS)
    published = sql_literal(PUBLISHED_AT)
    return """-- Batch B marking runtime: explicit requires_review mode and versioned apply helper.
-- Does not invent scoring. requires_review and completion remain pending evidence.
begin;

create or replace function learning.mark_evidence_response(
  p_question_id uuid,
  p_payload jsonb,
  p_max_score numeric
)
returns table (
  awarded_score numeric(8,2),
  is_correct boolean,
  requires_review boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_spec jsonb;
  v_mode text;
  v_source text;
  v_pattern text;
  v_ok boolean;
  v_option text;
  v_category text;
begin
  select marking.spec
  into v_spec
  from learning.question_marking as marking
  where marking.question_id = p_question_id;

  v_mode := coalesce(v_spec ->> 'mode', 'completion');
  v_option := coalesce(
    nullif(p_payload ->> 'optionId', ''),
    nullif(p_payload ->> 'selectedOptionId', ''),
    nullif(p_payload ->> 'option_id', ''),
    nullif(p_payload ->> 'selected_option_id', '')
  );
  v_category := coalesce(
    nullif(p_payload ->> 'categoryId', ''),
    nullif(p_payload ->> 'category', ''),
    nullif(p_payload ->> 'category_id', '')
  );

  if v_mode = 'single-choice' then
    v_ok := coalesce(v_option, '') = coalesce(v_spec ->> 'correctOptionId', '');
    awarded_score := case when v_ok then p_max_score else 0 end;
    is_correct := v_ok;
    requires_review := false;
    return next;
    return;
  end if;

  if v_mode = 'classification' then
    v_ok := coalesce(v_category, '') = coalesce(v_spec ->> 'correctCategoryId', '');
    awarded_score := case when v_ok then p_max_score else 0 end;
    is_correct := v_ok;
    requires_review := false;
    return next;
    return;
  end if;

  if v_mode = 'python-patterns' then
    v_source := coalesce(p_payload ->> 'sourceCode', '');
    v_ok := true;
    for v_pattern in
      select jsonb_array_elements_text(coalesce(v_spec -> 'required', '[]'::jsonb))
    loop
      if v_source !~ v_pattern then
        v_ok := false;
      end if;
    end loop;
    for v_pattern in
      select jsonb_array_elements_text(coalesce(v_spec -> 'prohibited', '[]'::jsonb))
    loop
      if v_source ~ v_pattern then
        v_ok := false;
      end if;
    end loop;
    awarded_score := case when v_ok then p_max_score else 0 end;
    is_correct := v_ok;
    requires_review := false;
    return next;
    return;
  end if;

  if v_mode in ('completion', 'requires_review') then
    awarded_score := 0;
    is_correct := null;
    requires_review := true;
    return next;
    return;
  end if;

  awarded_score := 0;
  is_correct := null;
  requires_review := true;
  return next;
end;
$$;

revoke all on function learning.mark_evidence_response(uuid, jsonb, numeric)
  from public, anon, authenticated;

create or replace function learning.apply_unit3_batch_b_marking(catalogue jsonb)
returns void
language plpgsql
set search_path = ''
as $batchb$
declare
  item jsonb;
  expected jsonb;
  source_question learning.questions%rowtype;
  v_activity_id uuid;
  v_source learning.activity_versions%rowtype;
  v_new learning.activity_versions%rowtype;
  v_new_id uuid;
  v_question_id uuid;
  v_type text;
  v_score numeric;
  v_spec jsonb;
  v_expected_count integer;
  v_source_count integer;
  v_week_id uuid;
  v_max numeric;
  v_hash text;
begin
  if jsonb_typeof(catalogue) is distinct from 'array' then
    raise exception 'UNIT3_BATCH_B_CONFLICT: catalogue must be a JSON array';
  end if;

  for item in
    select value from jsonb_array_elements(catalogue)
  loop
    select id into strict v_activity_id
    from learning.activities
    where stable_key = item->>'activityKey';

    select version.* into v_source
    from learning.activity_versions as version
    where version.activity_id = v_activity_id
      and version.version = item->>'sourceVersion';

    if not found or v_source.published_at is null or v_source.retired_at is not null then
      raise exception 'UNIT3_BATCH_B_CONFLICT: missing published source % %', item->>'activityKey', item->>'sourceVersion';
    end if;

    select count(*)::integer into v_source_count
    from learning.questions
    where activity_version_id = v_source.id;
    v_expected_count := jsonb_array_length(item->'questions');
    if v_source_count is distinct from v_expected_count then
      raise exception 'UNIT3_BATCH_B_CONFLICT: % % question count drifted', item->>'activityKey', item->>'sourceVersion';
    end if;

    select count(*)::integer into v_source_count
    from jsonb_array_elements(item->'questions') as expected
    join learning.questions as question
      on question.activity_version_id = v_source.id
     and question.stable_key = expected.value->>'k';
    if v_source_count is distinct from v_expected_count then
      raise exception 'UNIT3_BATCH_B_CONFLICT: % % question keys drifted', item->>'activityKey', item->>'sourceVersion';
    end if;

    v_new_id := extensions.uuid_generate_v5(
      __UUID_NS__::uuid,
      'version:' || (item->>'activityKey') || ':' || (item->>'newVersion')
    );

    v_max := 0;
    v_hash := encode(
      extensions.digest(item::text, 'sha256'),
      'hex'
    );

    insert into learning.activity_versions (
      id, activity_id, version, content_hash, max_score, question_count, published_at
    )
    values (
      v_new_id,
      v_activity_id,
      item->>'newVersion',
      v_hash,
      v_source.max_score,
      v_expected_count,
      null
    )
    on conflict (activity_id, version) do nothing;

    select * into strict v_new
    from learning.activity_versions
    where id = v_new_id;

    if v_new.published_at is not null then
      continue;
    end if;

    for expected in
      select value from jsonb_array_elements(item->'questions')
    loop
      select * into strict source_question
      from learning.questions
      where activity_version_id = v_source.id
        and stable_key = expected->>'k';

      v_type := coalesce(expected->>'qt', source_question.question_type);
      v_score := coalesce((expected->>'ms')::numeric, source_question.max_score);
      v_max := v_max + v_score;
      v_question_id := extensions.uuid_generate_v5(
        __UUID_NS__::uuid,
        'question:' || (item->>'activityKey') || ':' || (item->>'newVersion') || ':' || (expected->>'k')
      );

      insert into learning.questions (
        id, activity_version_id, stable_key, section_key, section_title, question_type, analytics_title, ordinal, max_score
      )
      values (
        v_question_id,
        v_new.id,
        source_question.stable_key,
        source_question.section_key,
        source_question.section_title,
        v_type,
        source_question.analytics_title,
        source_question.ordinal,
        v_score
      )
      on conflict (activity_version_id, stable_key) do nothing;

      v_spec := jsonb_build_object('mode', expected->>'m');
      if expected ? 'o' then
        v_spec := v_spec || jsonb_build_object('correctOptionId', expected->>'o');
      end if;
      if expected ? 'c' then
        v_spec := v_spec || jsonb_build_object('correctCategoryId', expected->>'c');
      end if;

      insert into learning.question_marking (question_id, spec)
      values (v_question_id, v_spec)
      on conflict (question_id) do nothing;
    end loop;

    update learning.activity_versions
    set max_score = v_max,
        content_hash = v_hash,
        published_at = __PUBLISHED_AT__::timestamptz
    where id = v_new.id
      and published_at is null;

    v_week_id := (
      select id
      from learning.curriculum_weeks
      where module_id = (
        select id from learning.modules
        where course_id = (select id from learning.courses where stable_key = 'ocr-level-3-it')
          and stable_key = 'unit-3-cyber-security'
      )
        and stable_key = 'week-' || (item->>'weekNumber')
    );

    insert into learning.activity_delivery (
      activity_version_id, academic_year_id, curriculum_week_id, week_number, session_number, sort_order, active
    )
    select
      v_new.id,
      academic_year.id,
      v_week_id,
      (item->>'weekNumber')::integer,
      coalesce(
        nullif(item->>'sessionNumber', '')::integer,
        (
          select delivery.session_number
          from learning.activity_delivery as delivery
          where delivery.activity_version_id = v_source.id
          order by delivery.active desc
          limit 1
        )
      ),
      0,
      true
    from learning.academic_years as academic_year
    where academic_year.active
      and not exists (
        select 1
        from learning.activity_delivery as delivery
        where delivery.activity_version_id = v_new.id
          and delivery.academic_year_id = academic_year.id
          and delivery.group_id is null
      )
    order by academic_year.code
    limit 1;

    insert into learning.activity_assignments (id, group_id, activity_version_id, required, active)
    select
      extensions.uuid_generate_v5(
        __UUID_NS__::uuid,
        'assignment:CYBER-TEST-A:' || (item->>'activityKey') || ':' || (item->>'newVersion')
      ),
      learner_group.id,
      v_new.id,
      true,
      true
    from learning.groups as learner_group
    where learner_group.code = 'CYBER-TEST-A'
    on conflict (group_id, activity_version_id) do nothing;
  end loop;
end;
$batchb$;

revoke all on function learning.apply_unit3_batch_b_marking(jsonb) from public, anon, authenticated;

commit;
""".replace("__UUID_NS__", ns).replace("__PUBLISHED_AT__", published)


def generate_sql(policies_doc: dict) -> dict[str, str]:
    activities = compact_activities(policies_doc["policies"])
    files = {
        "20260830230000_unit3_batch_b_marking_runtime.sql": runtime_sql(),
    }
    for filename, weeks in WEEK_GROUPS:
        subset = [item for item in activities if item["weekNumber"] in weeks]
        files[filename] = emit_week_migration(filename, subset)
    return files


def write_outputs(policies_doc: dict) -> dict[str, Path]:
    MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    policies_path = MANIFEST_DIR / "marking-policies.json"
    policies_path.write_text(json.dumps(policies_doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    written = {"policies": policies_path}
    for filename, sql in generate_sql(policies_doc).items():
        path = MIGRATION_DIR / filename
        path.write_text(sql, encoding="utf-8")
        written[filename] = path
    return written


def generate_from_catalogue(catalogue_rows: list[dict]) -> dict:
    return build_policies(catalogue_rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalogue", type=Path, default=MANIFEST_DIR / "source-catalogue.json")
    parser.add_argument("--refresh-policies", action="store_true")
    args = parser.parse_args()
    if args.refresh_policies:
        rows = json.loads(args.catalogue.read_text(encoding="utf-8"))
        policies_doc = generate_from_catalogue(rows)
    else:
        policies_doc = json.loads((MANIFEST_DIR / "marking-policies.json").read_text(encoding="utf-8"))
    written = write_outputs(policies_doc)
    for label, path in written.items():
        print(f"{label}: {path} ({path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
