#!/usr/bin/env python3
"""Assemble a canonical lp.content package into a local publication seed.

The seed inserts the reviewed package into platform.curriculum_publications and
projects the delivery catalogue. It does not author a second curriculum schema.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from content_package import PackageError, canonical_json, load_package, validate_package


def assemble_package(directory: Path) -> dict:
    package = load_package(directory)
    issues = validate_package(package)
    if issues:
        raise PackageError(issues[0].code, issues[0].path, issues[0].message)
    return {
        "schema": "lp.content.package",
        "schemaVersion": package.index["schemaVersion"],
        "id": package.index["id"],
        "version": package.index["version"],
        "hub": package.hub,
        "curriculum": package.curriculum,
        "learningOutcomes": package.learning_outcomes,
        "assignments": package.assignments,
        "weeks": package.weeks,
        "sessions": package.sessions,
        "activities": package.activities,
        "questions": [],
        "assets": [],
    }


def generate_seed_sql(
    package: dict,
    *,
    hub_code: str,
    course_key: str,
    project_catalogue: bool = True,
) -> str:
    body = canonical_json(package)
    version = package["version"]
    author = f"Canonical package import for {hub_code}"
    notes = f"Reviewed curriculum package {version} for database-first learner delivery."
    projection_comment = (
        "  -- Grounded catalogue already imported for this hub; publication body is the learner runtime source."
        if not project_catalogue
        else ""
    )
    projection_call = (
        [
            "  perform platform.project_curriculum_package(",
            "    v_package,",
            f"    {hub_code!r},",
            f"    {course_key!r},",
            f"    {version!r},",
            "    v_publication_id",
            "  );",
        ]
        if project_catalogue
        else []
    )
    idempotent_call = (
        [
            "    perform platform.project_current_curriculum_catalogue(",
            f"      {hub_code!r},",
            f"      {course_key!r}",
            "    );",
        ]
        if project_catalogue
        else []
    )
    return "\n".join(
        [
            "-- Generated by scripts/import/generate-curriculum-publication-seed.py.",
            "-- Local seed only. Hosted publication uses Admin Publish to Platform.",
            "do $$",
            "declare",
            "  v_package jsonb;",
            "  v_hash text;",
            "  v_publication_id uuid;",
            "  v_admin learning.teachers%rowtype;",
            "begin",
            "  select teacher.*",
            "  into v_admin",
            "  from learning.teachers as teacher",
            "  where teacher.auth_user_id = '20000000-0000-4000-8000-000000000003'",
            "    and teacher.active;",
            "",
            "  if not found then",
            "    raise exception using errcode = 'P0001', message = 'PUBLICATION_SEED_ADMIN_MISSING';",
            "  end if;",
            "",
            f"  v_package := $lp_pkg${body}$lp_pkg$::jsonb;",
            "  v_hash := encode(extensions.digest(v_package::text, 'sha256'), 'hex');",
            "",
            "  select publication.id",
            "  into v_publication_id",
            "  from platform.curriculum_publications as publication",
            f"  where publication.hub_code = {hub_code!r}",
            f"    and publication.course_key = {course_key!r}",
            f"    and publication.package_version = {version!r};",
            "",
            "  if v_publication_id is not null then",
            *idempotent_call,
            "    return;",
            "  end if;",
            "",
            "  update platform.curriculum_publications",
            "  set status = 'superseded'",
            f"  where hub_code = {hub_code!r}",
            f"    and course_key = {course_key!r}",
            "    and status = 'published';",
            "",
            "  insert into platform.curriculum_publications (",
            "    hub_code, course_key, package_version, schema_version, source_package_version,",
            "    status, package, content_hash, author, reviewer, publication_notes,",
            "    published_by_auth_user_id, published_by_staff_reference",
            "  ) values (",
            f"    {hub_code!r},",
            f"    {course_key!r},",
            f"    {version!r},",
            "    '0.1.0',",
            "    '0.1.0',",
            "    'published',",
            "    v_package,",
            "    v_hash,",
            f"    {author!r},",
            "    'Curriculum review',",
            f"    {notes!r},",
            "    v_admin.auth_user_id,",
            "    v_admin.staff_reference",
            "  )",
            "  returning id into v_publication_id;",
            "",
            projection_comment,
            *projection_call,
            "end",
            "$$;",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a local publication seed from a canonical package.")
    parser.add_argument("package", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--publication-only",
        action="store_true",
        help="Insert the publication package without re-projecting an already-grounded catalogue.",
    )
    args = parser.parse_args()

    try:
        assembled = assemble_package(args.package)
    except PackageError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    hub_code = assembled["hub"]["id"]
    course_key = assembled["curriculum"]["metadata"]["course"]
    sql = generate_seed_sql(
        assembled,
        hub_code=hub_code,
        course_key=course_key,
        project_catalogue=not args.publication_only,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    print(
        f"Generated {args.output}: hub={hub_code} course={course_key} "
        f"version={assembled['version']} activities={len(assembled['activities'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
